#!/bin/bash

# ignore or change name of shell for comparing with diff
# commands to check
# 1
?>cat |
>|

# 2
?>cat |
>cat |
>cat |
>cat |ls-l

# error because of extra-prompt handling
// Marina's comment. I fixed my function is_open_pipe.
// Now it doesn't open extra prompt in these cases:
echo hi>|
echo hi | < |
echo hi |   |

# further commands
|
| echo oi
| |
| $
| >
>
>>
>>>
<
<<
echo hi <
cat    <| ls
echo hi | >
echo hi | > >>
echo hi |  "|"
